2024-03-04 18:00:31,756 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:02:15,579 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:03:53,017 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:05:47,846 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:06:24,439 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:06:42,503 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:06:50,438 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:14:57,961 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:15:40,596 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:16:03,329 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:17:10,103 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:18:23,963 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:18:23,964 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:26:24,492 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:26:24,494 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:26:39,368 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:26:43,124 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=480 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:27:47,936 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:27:49,785 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=536 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:29:06,991 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:29:06,998 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=480 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:29:45,175 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:29:45,183 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=348 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:30:24,851 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:30:24,857 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=536 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:31:59,482 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:31:59,490 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=524 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:32:12,407 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:32:12,418 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=492 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:34:32,209 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:34:32,216 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=348 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:35:13,545 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:35:13,551 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=496 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:36:02,995 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:36:03,002 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=524 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:38:52,771 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:38:52,779 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=536 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:39:50,594 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:39:50,601 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=524 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:40:09,286 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:40:09,293 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=496 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:41:58,380 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:41:58,389 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=348 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:43:15,039 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:43:15,046 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=496 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:44:14,774 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:44:14,782 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=348 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:46:27,054 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:46:27,060 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:46:27,065 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=544 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:46:40,567 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:46:40,572 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:46:40,577 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=480 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:49:43,680 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:49:43,685 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:49:43,691 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=348 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:49:45,501 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:592> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 597, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-04 18:51:03,267 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:51:03,268 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:51:24,158 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:51:33,928 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:51:42,571 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:51:46,534 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:17,551 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:17,552 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:17,555 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:592> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 597, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-04 18:52:19,809 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:19,811 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:19,813 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:592> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 597, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-04 18:52:41,545 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=904>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:52:41,593 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=944>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:52:47,022 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:47,024 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:52:47,027 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=1248 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 148, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 18:52:47,026 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:592> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 597, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-04 18:53:43,604 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:53:43,606 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:55:08,698 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:55:10,110 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:55:34,342 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:55:35,531 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:56:38,946 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:56:40,364 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:58:01,000 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:58:03,551 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:01,941 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:03,086 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:34,929 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:36,103 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:47,369 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:47,371 - DEBUG - Using proactor: IocpProactor
2024-03-04 18:59:47,374 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:592> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 597, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-04 18:59:47,376 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=1020 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 19:02:21,223 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:02:21,225 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:02:21,228 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=632 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 19:02:21,237 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:592>>
2024-03-04 19:03:48,522 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:03:48,524 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:03:48,527 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=884 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 19:03:48,544 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-04 19:04:11,882 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:04:25,996 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:04:34,565 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:04:34,567 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:04:34,571 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=628 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 19:04:59,275 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-04 19:05:20,876 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:05:20,878 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:05:25,286 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:05:25,292 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:05:25,297 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=460 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 19:06:04,746 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:06:04,751 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:06:04,756 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=520 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-04 19:08:59,364 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:08:59,369 - DEBUG - Using proactor: IocpProactor
2024-03-04 19:08:59,374 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=440 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 151, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-05 15:45:41,859 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:46:55,780 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:47:40,844 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:48:11,188 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:48:32,074 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:49:06,121 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:49:22,917 - DEBUG - Using proactor: IocpProactor
2024-03-05 15:50:41,626 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:00:03,526 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:00:45,551 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:00:59,431 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:00:59,432 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:00:59,437 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=860 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 160, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-05 16:01:27,195 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:02:21,007 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:02:21,009 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:02:23,208 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=808 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 160, in handle_client
    with self.lock:
TypeError: 'Lock' object does not support the context manager protocol
2024-03-05 16:02:40,953 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:02:47,683 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:02:49,140 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:02:49,141 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:05:31,497 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:06:22,661 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:14:26,361 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:14:34,150 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:14:34,152 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:15:08,240 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:15:12,932 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:15:15,000 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:15:15,001 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:17:50,385 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:17:58,891 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:18:01,057 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:18:01,059 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:18:49,947 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:18:52,164 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:18:52,166 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:20:07,131 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:20:18,404 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:20:20,444 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:20:20,445 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:21:41,803 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:21:52,128 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:21:57,648 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:21:57,650 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:23:13,043 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:23:16,393 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:23:17,839 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:23:17,841 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:35:06,384 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:35:09,165 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:35:10,224 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:35:10,225 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:35:41,084 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:595>>
2024-03-05 16:35:47,988 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:38:27,451 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:38:42,455 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:38:42,461 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:45:15,490 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:45:39,893 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=484 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 16:47:23,540 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:47:55,137 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:48:25,842 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:48:58,941 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:49:41,215 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:50:50,177 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:50:52,615 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 16:51:21,316 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:51:29,536 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:51:31,962 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:606> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 611, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 16:52:01,548 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:52:02,115 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 16:52:24,312 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-05 16:52:26,567 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:52:33,018 - DEBUG - Using proactor: IocpProactor
2024-03-05 16:52:33,592 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:00:09,552 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-05 17:00:19,056 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:00:27,337 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:00:27,895 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:01:14,023 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:01:25,275 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-05 17:01:29,717 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:01:34,917 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:01:43,551 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:02:26,324 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:02:29,854 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:04:15,304 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:04:19,089 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:04:20,384 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:05:27,536 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:05:31,998 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:05:33,160 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:06:23,540 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:06:27,583 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:06:28,576 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:25:31,604 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:25:33,143 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:25:34,604 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=976 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 17:25:41,241 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:25:48,851 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:25:53,688 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:26:10,058 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:26:18,693 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:26:28,489 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:26:31,244 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:605> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 610, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:27:11,029 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:27:13,786 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:608> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 613, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:27:36,696 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:27:43,198 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:27:43,755 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<IEC104Client.periodic_event_check() done, defined at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:608> exception=AttributeError("'IEC104Client' object has no attribute 'clients'")>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py", line 613, in periodic_event_check
    for client in self.clients:
                  ^^^^^^^^^^^^
AttributeError: 'IEC104Client' object has no attribute 'clients'
2024-03-05 17:28:26,514 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:29:07,215 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:35:15,996 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-05 17:54:40,131 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:55:06,466 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:55:51,902 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:55:57,017 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:57:23,531 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:57:23,538 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=312 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 17:58:00,698 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:58:00,706 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=508 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 17:58:51,098 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:58:51,106 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=312 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 17:59:23,379 - DEBUG - Using proactor: IocpProactor
2024-03-05 17:59:23,389 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=508 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:01:22,901 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:01:22,908 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:28:51,659 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:28:51,667 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=500 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:29:19,842 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:29:19,850 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=484 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:32:35,904 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:32:35,913 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=500 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:33:34,454 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:33:34,462 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=312 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:34:05,103 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:34:05,111 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=500 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:35:09,484 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:35:09,493 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:35:22,136 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:35:22,143 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=488 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:35:48,314 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:36:27,803 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:38:04,382 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:38:04,390 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=528 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:38:28,672 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:38:28,680 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=508 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:40:18,658 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:40:18,666 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=524 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 167, in handle_client
    self.active_session = self.queue.Select_active_session(session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 148, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 105, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-05 18:40:42,272 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:41:07,653 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:43:01,741 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-05 18:43:03,942 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:43:15,986 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:57:26,347 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:59:36,437 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-05 18:59:46,858 - DEBUG - Using proactor: IocpProactor
2024-03-05 18:59:59,322 - DEBUG - Using proactor: IocpProactor
2024-03-05 19:00:17,828 - DEBUG - Using proactor: IocpProactor
2024-03-05 20:18:50,894 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:134> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 14:49:03,939 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:00:17,004 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:05:21,379 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:05:47,229 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:06:13,067 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:07:31,374 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:08:20,371 - DEBUG - Using proactor: IocpProactor
2024-03-06 15:12:56,564 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:03:15,078 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:05:54,898 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:08:35,102 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:09:42,402 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:14:40,530 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:16:14,414 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:20:44,895 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:21:31,722 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:21:49,893 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:23:50,430 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:35:35,187 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:35:50,082 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:35:50,193 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=548 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 170, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 57, in handle_apdu
    await self.session.update_state_machine(apdu)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'update_state_machine'. Did you mean: 'update_state_machine_client'?
2024-03-06 16:35:58,019 - WARNING - socket.send() raised exception.
2024-03-06 16:35:59,127 - WARNING - socket.send() raised exception.
2024-03-06 16:36:00,243 - WARNING - socket.send() raised exception.
2024-03-06 16:36:01,365 - WARNING - socket.send() raised exception.
2024-03-06 16:36:02,404 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-2' coro=<IEC104Client.periodic_event_check() running at d:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\client_async.py:469> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 16:40:01,060 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:40:34,732 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:132> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 16:40:42,155 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:40:47,694 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:40:47,804 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 170, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 57, in handle_apdu
    await self.session.update_state_machine(apdu)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'update_state_machine'. Did you mean: 'update_state_machine_client'?
2024-03-06 16:40:55,620 - WARNING - socket.send() raised exception.
2024-03-06 16:40:56,737 - WARNING - socket.send() raised exception.
2024-03-06 16:40:57,858 - WARNING - socket.send() raised exception.
2024-03-06 16:40:58,978 - WARNING - socket.send() raised exception.
2024-03-06 16:41:00,100 - WARNING - socket.send() raised exception.
2024-03-06 16:41:01,219 - WARNING - socket.send() raised exception.
2024-03-06 16:41:02,325 - WARNING - socket.send() raised exception.
2024-03-06 16:41:41,227 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:41:51,779 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:41:51,895 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=528 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 170, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 57, in handle_apdu
    await self.session.update_state_machine(apdu)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'update_state_machine'. Did you mean: 'update_state_machine_client'?
2024-03-06 16:41:59,718 - WARNING - socket.send() raised exception.
2024-03-06 16:42:00,827 - WARNING - socket.send() raised exception.
2024-03-06 16:42:01,951 - WARNING - socket.send() raised exception.
2024-03-06 16:42:03,064 - WARNING - socket.send() raised exception.
2024-03-06 16:42:04,173 - WARNING - socket.send() raised exception.
2024-03-06 16:42:05,288 - WARNING - socket.send() raised exception.
2024-03-06 16:42:06,405 - WARNING - socket.send() raised exception.
2024-03-06 16:44:21,856 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:44:25,211 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:44:25,316 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=520 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 170, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 57, in handle_apdu
    await self.session.update_state_machine(apdu)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'update_state_machine'. Did you mean: 'update_state_machine_client'?
2024-03-06 16:44:33,139 - WARNING - socket.send() raised exception.
2024-03-06 16:44:34,250 - WARNING - socket.send() raised exception.
2024-03-06 16:44:35,360 - WARNING - socket.send() raised exception.
2024-03-06 16:44:36,480 - WARNING - socket.send() raised exception.
2024-03-06 16:44:37,605 - WARNING - socket.send() raised exception.
2024-03-06 16:44:38,720 - WARNING - socket.send() raised exception.
2024-03-06 16:44:39,830 - WARNING - socket.send() raised exception.
2024-03-06 16:44:54,345 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:44:54,352 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=524 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 16:45:20,313 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:45:20,320 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=492 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 16:46:02,244 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:46:10,189 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:46:10,324 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=528 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 170, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 57, in handle_apdu
    await self.session.update_state_machine(apdu)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'update_state_machine'. Did you mean: 'update_state_machine_client'?
2024-03-06 16:46:18,160 - WARNING - socket.send() raised exception.
2024-03-06 16:46:19,280 - WARNING - socket.send() raised exception.
2024-03-06 16:47:29,943 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:47:29,950 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=328 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 16:56:37,815 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:56:48,780 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:57:55,347 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:57:55,354 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=548 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 16:58:23,787 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:58:29,425 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:59:10,289 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:59:10,296 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=432 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 16:59:45,401 - DEBUG - Using proactor: IocpProactor
2024-03-06 16:59:45,408 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=180 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 17:00:17,748 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:00:17,755 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=428 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 17:01:20,249 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:01:20,256 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=344 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 17:01:48,730 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:01:48,737 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=428 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    if item[2].get_connection_state() == 'Connected' and \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 17:06:43,200 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:06:43,208 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=488 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 165, in handle_client
    self.active_session = self.queue.Select_active_session(new_session)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 159, in Select_active_session
    for item in self.sessions_tuple:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 103, in get_connection_state
    return self.connection_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 17:07:31,426 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:132> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 17:09:41,352 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:09:48,102 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:11:26,506 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:132> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 17:11:27,822 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:11:33,681 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:13:28,459 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:13:35,436 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:17:40,931 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:17:46,066 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:19:01,001 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:19:28,510 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:23:42,834 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:132> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 17:23:44,925 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:23:51,452 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:24:45,214 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:24:50,981 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:42:34,908 - DEBUG - Using proactor: IocpProactor
2024-03-06 17:42:34,916 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 170, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 58, in handle_apdu
    await self.session.update_state_machine(apdu)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'update_state_machine'. Did you mean: 'update_state_machine_client'?
2024-03-06 21:10:04,765 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:132> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 21:10:08,383 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:11:29,155 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:11:55,531 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:12:38,648 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:13:07,718 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:13:16,561 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:13:16,564 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=548 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 164, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 141, in handle_apdu
    await self.session.update_state_machine_server(apdu)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 317, in update_state_machine_server
    await self.send_frame(new_frame)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 222, in send_frame
    self.writer.write(frame.serialize())
                      ^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'serialize'
2024-03-06 21:48:55,710 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:48:58,485 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:55:48,229 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:137> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 21:55:50,510 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:55:53,668 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:56:09,858 - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-1' coro=<ServerIEC104.start() running at D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py:137> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at C:\Users\slary\.pyenv\pyenv-win\versions\3.12.1\Lib\asyncio\tasks.py:767]>
2024-03-06 21:58:37,034 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:58:39,238 - DEBUG - Using proactor: IocpProactor
2024-03-06 21:58:39,242 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=520 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\server_async_v2.3-state_machine.py", line 164, in handle_client
    await self.queue.handle_apdu(request)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\QueueManager.py", line 141, in handle_apdu
    await self.session.update_state_machine_server(apdu)
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 332, in update_state_machine_server
    if self.get_transmission_state() == 'RUNNING':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\01-skola\vysoka\2021-2024\6.semestr\bakalarska_prace\IEC104\IEC104_SERVER\v2.0\Session.py", line 118, in get_transmission_state
    return self.transmission_state.get_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_state'
2024-03-06 22:07:38,422 - DEBUG - Using proactor: IocpProactor
2024-03-06 22:07:41,449 - DEBUG - Using proactor: IocpProactor
2024-03-06 22:07:57,111 - DEBUG - Using proactor: IocpProactor
2024-03-06 22:08:02,906 - DEBUG - Using proactor: IocpProactor
2024-03-06 22:08:05,781 - DEBUG - Using proactor: IocpProactor
2024-03-06 22:08:11,870 - DEBUG - Using proactor: IocpProactor
2024-03-06 22:09:46,535 - DEBUG - Using proactor: IocpProactor
